package com.example.outletmanagement.model.enums;

public enum NotificationType {
    STOCK_ORDER_CREATED,
    STOCK_ORDER_APPROVED,
    STOCK_ORDER_CANCELLED,
    LOW_STOCK_ALERT,
    NEW_USER_REGISTERED,
    IMPORT_COMPLETED,
    AUDIT_ACTION,
    // Phase 10+
    SHIPMENT_RECEIVED,
    BATCH_QUARANTINED,
    SYNC_FAILED,
    DEAD_LETTER_ALERT,
    RECONCILIATION_MISMATCH,
    QUARANTINE_APPROVAL_REQUIRED,
    RETURN_REJECTED,
    LOW_STOCK_CRITICAL,
    INFO,
    SUCCESS,
    WARNING,
    ERROR
}
